### ISSUE TITLE
`sao template` can't work

### ISSUE THREAD

**Issue by SidKwok** [egoist/template-template#2]
```
→ sao template template-name
ERROR You don’t seem to have a template with the name `template` installed.
? Let SAO install missing template for you? Yes
> Installing template-template...
ERROR Error: Cannot find module '/usr/local/lib/node_modules/template-template/package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/sao/lib/index.js:80:24
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/sao/node_modules/_co@4.6.0@co/index.js:65:19)
```

sao: 0.19.8
node: 6.11.4

**Comment by egoist** [comment]
Try the latest version of SAO?

**Comment by SidKwok** [comment]
Solved. Thanks!
